name: Abxplore

on:
  schedule:
    - cron: '15 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Abxplore bot"
      
      - name: updating Abxplore
        run: sh ressources/ftv/py/Abxplore.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Abxplore updated"
          git push
