name: CStar action

on:
  schedule:
    - cron: '15 */06 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "CStar bot"
      
      - name: updating eqpetv
        run: python3 ${GITHUB_WORKSPACE}/ressources/dm/py/dmfr/Cstar.py > ${GITHUB_WORKSPACE}/ressources/dm/py/hls/CStar.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "CStar updated"
          git push
