name: E1 action

on:
  schedule:
    - cron: '57 */5 * * *'
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "E1 bot"
      
      - name: updating lcpan
        run: python3 ressources/dmotion/py/E1/E1.py > ressources/dmotion/py/E1/E1.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "E1 updated"
          git push
