name: Equidia action

on:
  schedule:
    - cron: '55 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "equidia bot"
      
      - name: updating Equidia
        run: sh ressources/equidia/py/equidia.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Equidia updated"
          git push
