name: France3Regions action

on:
  schedule:
    - cron: '30 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "France3Regions bot"
      
      - name: updating fidf
        run: sh ressources/ftv/py/France3Regions.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "France3Regions updated"
          git push
