name: FranceTV action

on:
  schedule:
    - cron: '23 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "FranceTV bot"
      
      - name: updating FranceTV
        run: sh ressources/ftv/py/FranceTV.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "FranceTV updated"
          git push
