name: LCI action
on:
  schedule:
    - cron: "08 */3 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2

      - name: updating lci
        run: sh ressources/btv/py/LCI_b.sh

      - name: setup git config
        run: |
          git config user.name "LCI bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git add all.m3u
          git commit -m "LCI updated"
          git push origin master
