name: Azur FM Belgique action

on:
  schedule:
    - cron: '15 */06 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Azur FM Belgique bot"
      
      - name: updating eqpetv
        run: python3 twitch.py azurfmbelgique > Azurfmbelgique.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Azur FM Belgique updated"
          git push
