name: Lequipe action

on:
  schedule:
    - cron: '52 */5 * * *'
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Lequipe bot"
      
      - name: updating Lequipe
        run: sh ressources/dm/py/Lequipe.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Lequipe updated"
          git push
