# This is a basic workflow to help you get started with Actions
# Thanks to pshanmu3 user on github
name: Sardegna 1 action

# Controls when the workflow will run
on:
  schedule:
    - cron: '25 */5 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Sardegna 1 bot"
      
      - name: updating Sardegna 1
        run: sh ressources/dmotion/py/Locales/Sardegna1.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 

      - name: commit & push
        run: |
          git commit -m "Sardegna 1 updated"
          git push
