name: merge channels list

on:
  schedule:
    - cron: '0 6 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "admin bot"
      
      - name: updating tf1
        run: sh ${GITHUB_WORKSPACE}/tools/tf1plus.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "playlists merged"
          git push
