nom : TL7

on:
  schedule:
    - cron: '0 */4 * * *'
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

       
      - name: get config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"

      
      - name: grab twitch stream
        run: |
          pwd
          python3 twitch.py ​​tl7loire > ../../ressources/twitch/hls/TL7.m3u8
        
      - nom : tout ajouter
        courir: |
          git add -A
          ls-la
          
      - nom : commit & push
        courir: |
          git commit -m "TL7 mise à jour"
          git push
